pipeline {
    agent any
    stages {
        stage('Example Stage') {
            steps {
                echo 'Hello, world!'
            }
        }
        stage('Checkout') {
            steps {
                echo 'Starting checkout...'
                git branch: 'main', url: 'https://github.com/ansariakbar786/motogp-ms.git'
                echo 'Checkout complete.'
            }
        }
        stage('Build') {
            steps {
                echo 'Starting build...'
                sh 'mvn clean install'
                echo 'Build complete.'
            }
        }
    }
    post {
        always {
            // Clean up tasks
            echo "Pipeline completed."
        }
        success {
            echo "Build succeeded!"
        }
        failure {
            echo "Build failed!"
        }
    }
}
