pipeline {
    agent {
        docker {
            image 'maven:3.8.6-jdk-11' // Or your preferred Maven and JDK version
            args '-v $HOME/.m2:/root/.m2' // Optional: Cache Maven dependencies
        }
    }
    stages {
        stage('Example Stage') {
            steps {
                echo 'Hello, world!'
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ansariakbar786/motogp-ms.git'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean install' // Or your preferred Maven goals
            }
        }
        stage('Quality Checks') {
            steps {
                sh 'mvn pmd:pmd' //Optional: PMD Integration
            }
        }
        stage('Deploy') {
            when {
                branch 'main' // Deploy only from main branch
            }
            steps {
                // Add your deployment steps here (e.g., deploying to a server, pushing a Docker image)
                echo "Deploying application..."
            }
        }
    }
    post {
        always {
            // Clean up tasks
            echo "Pipeline completed."
        }
        success {
            echo "Build succeeded!"
        }
        failure {
            echo "Build failed!"
        }
    }
}
