server: 
   port: 8087
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empDB
    username: root
    password: 
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  data: 
     mongodb: 
       authentication-database: admin
       database: customerDB
       username: admin
       password: password
       host: 127.0.0.1
       #uri: mongodb://localhost:27017/customerDB
springdoc:
   swagger-ui:
      path: /swagger-ui.html
   api-docs:
      path: /openapi/v3/api-docs
   packagesToScan: com.motorola.io.motogp.controller
   pathsToMatch: /**
    